const { catchAsyncErrors } = require('../middlewares/catchAsyncError')
const { User, Address } = require('../models/userModel');
const nodemailer=require('nodemailer')
const Admin = require('../models/adminModel')
const { sendToken } = require('../utils/sendToken');
const bcrypt = require('bcryptjs')
const { sendmail } = require('../utils/nodemailer')
const mongoose = require('mongoose')
const ContactUs=require('../models/contact')
const ErrorHandler = require('../utils/ErrorHandler')
const imagekitClient=require('../utils/imagekit').initimagekit()
const {paymentInitialisation} = require('./paymentController');
const {v4: uuidv4 } = require('uuid');